# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.

trigger:
- main
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: StoreWebBuildPool-Centeral
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: job
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish build artifact'
            targetPath: '$(System.DefaultWorkingDirectory)/dist'
            artifactName: 'ms-store-badge-artifacts'
            publishLocation: 'Container'
        steps:
        - checkout: self
          submodules: true

        - script: |
            icacls "$(Build.SourcesDirectory)" /grant Everyone:F /T
            if exist "$(Build.SourcesDirectory)\.npmrc" (
              dir "$(Build.SourcesDirectory)\.npmrc"
            ) else (
              echo .npmrc file not found
              echo. > "$(Build.SourcesDirectory)\.npmrc"
            )
          displayName: 'Add vsts directory permissions'

        - script: |
            npm install -g typescript
          displayName: 'Install TypeScript'

        - task: NpmAuthenticate@0
          inputs:
            workingFile: '.npmrc'
          displayName: 'Authenticate to NPM'

        - script: |
            echo "Cleaning dist directory"
            rm -rf "$(System.DefaultWorkingDirectory)/dist"
          displayName: 'Clean dist directory'

        - script: |
            npm install
          displayName: 'Install dependencies'

        - script: |
            echo "Listing current directory contents:"
            dir
          displayName: 'List directory contents after install'

        - script: |
            cd src
            tsc -t es2015 --moduleResolution node ms-store-badge.ts
          displayName: 'Compile TypeScript'
          
        - script: |
            npm run build:prod
          displayName: 'Build badge'

        - script: |
            echo "Listing dist directory structure:"
            dir dist /s
          displayName: 'List dist directory structure'
          
        - script: |
            echo "Listing current directory contents:"
            dir
          displayName: 'List current directory contents after build'

        - script: |
            echo "Setting up GitHub repository"
            git config --global user.name "Justin Lau"
            git config --global user.email "justinlau@microsoft.com"
            git remote add github https://$(GITHUB_TOKEN)@github.com/microsoft/app-store-badge.git
            git fetch github
            git checkout github/main
            git merge origin/main -X ours --allow-unrelated-histories --no-edit
            git rm .npmrc -f
            git add -A
            git commit -m "Sync from ADO repo" || echo "No changes to commit"
            git push github HEAD:main --force
          displayName: 'Sync ADO Repo to GitHub'
          env:
            GITHUB_TOKEN: $(GITHUB_TOKEN)