trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

    # Authenticate npm
  - script: |
      npm install -g vsts-npm-auth 
      vsts-npm-auth -config .npmrc
    displayName: 'Authenticate npm registry'
    
  # Build steps for the project
  - script: |
      cd src
      tsc -t es2015 ms-store-badge.ts
      npm install
      npm run build:prod
    displayName: 'Build Project'

  # Deploy to Azure Static Web App
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/' 
      api_location: '' 
      output_location: '/dist'  # Built app content directory relative to app_location
      azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
      ArtifactName: 'ms-store-badge-artifacts'
      publishLocation: 'Container'
