# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.

trigger:
- main
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: StoreWebBuildPool-Centeral
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: job
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish build artifact'
            targetPath: '$(System.DefaultWorkingDirectory)/dist'
            artifactName: 'ms-store-badge-artifacts'
            publishLocation: 'Container'
        steps:
        - checkout: self
          submodules: true

        - script: |
            icacls "$(Build.SourcesDirectory)" /grant Everyone:F /T
            if exist "$(Build.SourcesDirectory)\.npmrc" (
              dir "$(Build.SourcesDirectory)\.npmrc"
            ) else (
              echo .npmrc file not found
              echo. > "$(Build.SourcesDirectory)\.npmrc"
            )
          displayName: 'Add vsts directory permissions'

        - script: |
            npm install -g typescript
          displayName: 'Install TypeScript'

        - task: NpmAuthenticate@0
          inputs:
            workingFile: '.npmrc'
          displayName: 'Authenticate to NPM'
        
        - script: |
            
            # Clean up previous build artifacts
            rm -rf node_modules
            rm -rf dist
            
            # Install dependencies and build once
            npm cache clean --force
            npm install
            
            # Show debug info 
            echo "Files in current directory:"
            ls -la
            echo "Content of src directory:"
            ls -la src/
            
            # Run the production build (which should handle TypeScript compilation)
            npm run build:prod
            
            # Verify build output
            echo "Build complete, checking output:"
            ls -la dist/
          displayName: 'Clean build'
          
        - script: |
            echo "Setting up GitHub repository"
              # Configure Git to use the stored GitHub token
            git config --global user.name "Justin Lau"
            git config --global user.email "justinlau@microsoft.com"
              # Add remote GH badge repo
            git remote add github https://$(GITHUB_TOKEN)@github.com/microsoft/app-store-badge.git
              # Fetch the latest changes
            git fetch github
              # Ensure we are on the GH main branch
            git checkout github/main
              # Merge changes from ADO repository, take our side by default, and allow unrelated histories
            git merge origin/main -X ours --allow-unrelated-histories --no-edit
              # Remove .npmrc file
            git rm .npmrc -f
              # Add changes
            git add -A
              # Commit changes
            git commit -m "Sync from ADO repo" || echo "No changes to commit"
              # Push the changes to GH
            git push github HEAD:main --force
          displayName: 'Sync ADO Repo to GitHub'
          env:
            GITHUB_TOKEN: $(GITHUB_TOKEN)